name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  


    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Убедимся, что клонируем нужную ветку

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Устанавливаем Node.js версии 14

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install  # Устанавливаем все зависимости проекта

      # Шаг 4: Сборка проекта
      - name: Build project
        run: npm run build  # Строим проект, результат попадет в ./dist

      # Шаг 5: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Используем токен для авторизации
          publish_dir: ./dist  # Публикуем содержимое из папки dist
          publish_branch: feat-1  # Публикуем на ветке gh-pages
